package neu.edu.entity;
// Generated 16-Dec-2022, 3:02:55 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customerorder generated by hbm2java
 */
@Entity
@Table(name = "customerorder", catalog = "distributer")
public class Customerorder implements java.io.Serializable {

	private String orderid;
	private Integer productid;
	private String productname;
	private Integer units;
	private Integer cost;
	private String status;
	private String distributerid;

	public Customerorder() {
	}

	public Customerorder(String orderid) {
		this.orderid = orderid;
	}

	public Customerorder(String orderid, Integer productid, String productname, Integer units, Integer cost,
			String status, String distributerid) {
		this.orderid = orderid;
		this.productid = productid;
		this.productname = productname;
		this.units = units;
		this.cost = cost;
		this.status = status;
		this.distributerid = distributerid;
	}

	@Id

	@Column(name = "orderid", unique = true, nullable = false, length = 50)
	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	@Column(name = "productid")
	public Integer getProductid() {
		return this.productid;
	}

	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	@Column(name = "productname", length = 50)
	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	@Column(name = "units")
	public Integer getUnits() {
		return this.units;
	}

	public void setUnits(Integer units) {
		this.units = units;
	}

	@Column(name = "cost")
	public Integer getCost() {
		return this.cost;
	}

	public void setCost(Integer cost) {
		this.cost = cost;
	}

	@Column(name = "status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "distributerid", length = 50)
	public String getDistributerid() {
		return this.distributerid;
	}

	public void setDistributerid(String distributerid) {
		this.distributerid = distributerid;
	}

}
