package neu.edu.entity;
// Generated 16-Dec-2022, 3:02:55 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "distributer")
public class Product implements java.io.Serializable {

	private String productupc;
	private Integer productid;
	private String productname;
	private Integer availability;
	private Integer cost;
	private String distributerid;

	public Product() {
	}

	public Product(String productupc) {
		this.productupc = productupc;
	}

	public Product(String productupc, Integer productid, String productname, Integer availability, Integer cost,
			String distributerid) {
		this.productupc = productupc;
		this.productid = productid;
		this.productname = productname;
		this.availability = availability;
		this.cost = cost;
		this.distributerid = distributerid;
	}

	@Id

	@Column(name = "productupc", unique = true, nullable = false, length = 50)
	public String getProductupc() {
		return this.productupc;
	}

	public void setProductupc(String productupc) {
		this.productupc = productupc;
	}

	@Column(name = "productid")
	public Integer getProductid() {
		return this.productid;
	}

	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	@Column(name = "productname", length = 50)
	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	@Column(name = "availability")
	public Integer getAvailability() {
		return this.availability;
	}

	public void setAvailability(Integer availability) {
		this.availability = availability;
	}

	@Column(name = "cost")
	public Integer getCost() {
		return this.cost;
	}

	public void setCost(Integer cost) {
		this.cost = cost;
	}

	@Column(name = "distributerid", length = 50)
	public String getDistributerid() {
		return this.distributerid;
	}

	public void setDistributerid(String distributerid) {
		this.distributerid = distributerid;
	}

}
