package neu.edu.entity;
// Generated 13-Dec-2022, 10:53:03 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "supplier")
public class Orders implements java.io.Serializable {

	private int orderid;
	private Integer itemid;
	private String itemname;
	private Integer units;
	private Integer cost;
	private String status;
	private String supplierid;

	public Orders() {
	}

	public Orders(int orderid) {
		this.orderid = orderid;
	}

	public Orders(int orderid, Integer itemid, String itemname, Integer units, Integer cost, String status,
			String supplierid) {
		this.orderid = orderid;
		this.itemid = itemid;
		this.itemname = itemname;
		this.units = units;
		this.cost = cost;
		this.status = status;
		this.supplierid = supplierid;
	}

	@Id

	@Column(name = "orderid", unique = true, nullable = false)
	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	@Column(name = "itemid")
	public Integer getItemid() {
		return this.itemid;
	}

	public void setItemid(Integer itemid) {
		this.itemid = itemid;
	}

	@Column(name = "itemname", length = 50)
	public String getItemname() {
		return this.itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	@Column(name = "units")
	public Integer getUnits() {
		return this.units;
	}

	public void setUnits(Integer units) {
		this.units = units;
	}

	@Column(name = "cost")
	public Integer getCost() {
		return this.cost;
	}

	public void setCost(Integer cost) {
		this.cost = cost;
	}

	@Column(name = "status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "supplierid", length = 50)
	public String getSupplierid() {
		return this.supplierid;
	}

	public void setSupplierid(String supplierid) {
		this.supplierid = supplierid;
	}

}
