package neu.edu.entity;
// Generated 13-Dec-2022, 10:53:03 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "supplier")
public class Supplier implements java.io.Serializable {

	private String supplierid;
	private String weather;
	private String politicalissues;
	private String labourissues;
	private String driverissues;

	public Supplier() {
	}

	public Supplier(String supplierid) {
		this.supplierid = supplierid;
	}

	public Supplier(String supplierid, String weather, String politicalissues, String labourissues,
			String driverissues) {
		this.supplierid = supplierid;
		this.weather = weather;
		this.politicalissues = politicalissues;
		this.labourissues = labourissues;
		this.driverissues = driverissues;
	}

	@Id

	@Column(name = "supplierid", unique = true, nullable = false, length = 50)
	public String getSupplierid() {
		return this.supplierid;
	}

	public void setSupplierid(String supplierid) {
		this.supplierid = supplierid;
	}

	@Column(name = "weather", length = 50)
	public String getWeather() {
		return this.weather;
	}

	public void setWeather(String weather) {
		this.weather = weather;
	}

	@Column(name = "politicalissues", length = 50)
	public String getPoliticalissues() {
		return this.politicalissues;
	}

	public void setPoliticalissues(String politicalissues) {
		this.politicalissues = politicalissues;
	}

	@Column(name = "labourissues", length = 50)
	public String getLabourissues() {
		return this.labourissues;
	}

	public void setLabourissues(String labourissues) {
		this.labourissues = labourissues;
	}

	@Column(name = "driverissues", length = 50)
	public String getDriverissues() {
		return this.driverissues;
	}

	public void setDriverissues(String driverissues) {
		this.driverissues = driverissues;
	}

}
