package neu.edu.entity;
// Generated 14-Dec-2022, 10:01:30 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Distributerorder generated by hbm2java
 */
@Entity
@Table(name = "distributerorder", catalog = "manufacture")
public class Distributerorder implements java.io.Serializable {

	private int orderid;
	private Integer productid;
	private String productname;
	private Integer units;
	private Integer cost;
	private String status;
	private String manufactureid;
	private String distributerid;

	public Distributerorder() {
	}

	public Distributerorder(int orderid) {
		this.orderid = orderid;
	}

	public Distributerorder(int orderid, Integer productid, String productname, Integer units, Integer cost,
			String status, String manufactureid, String distributerid) {
		this.orderid = orderid;
		this.productid = productid;
		this.productname = productname;
		this.units = units;
		this.cost = cost;
		this.status = status;
		this.manufactureid = manufactureid;
		this.distributerid = distributerid;
	}

	@Id

	@Column(name = "orderid", unique = true, nullable = false)
	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	@Column(name = "productid")
	public Integer getProductid() {
		return this.productid;
	}

	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	@Column(name = "productname", length = 50)
	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	@Column(name = "units")
	public Integer getUnits() {
		return this.units;
	}

	public void setUnits(Integer units) {
		this.units = units;
	}

	@Column(name = "cost")
	public Integer getCost() {
		return this.cost;
	}

	public void setCost(Integer cost) {
		this.cost = cost;
	}

	@Column(name = "status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "manufactureid", length = 50)
	public String getManufactureid() {
		return this.manufactureid;
	}

	public void setManufactureid(String manufactureid) {
		this.manufactureid = manufactureid;
	}

	@Column(name = "distributerid", length = 50)
	public String getDistributerid() {
		return this.distributerid;
	}

	public void setDistributerid(String distributerid) {
		this.distributerid = distributerid;
	}

}
