package neu.edu.entity;
// Generated 14-Dec-2022, 10:01:30 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Manufacture generated by hbm2java
 */
@Entity
@Table(name = "manufacture", catalog = "manufacture")
public class Manufacture implements java.io.Serializable {

	private String manufactureid;
	private String weather;
	private String politicalissues;
	private String labourissues;
	private String driverissues;

	public Manufacture() {
	}

	public Manufacture(String manufactureid) {
		this.manufactureid = manufactureid;
	}

	public Manufacture(String manufactureid, String weather, String politicalissues, String labourissues,
			String driverissues) {
		this.manufactureid = manufactureid;
		this.weather = weather;
		this.politicalissues = politicalissues;
		this.labourissues = labourissues;
		this.driverissues = driverissues;
	}

	@Id

	@Column(name = "manufactureid", unique = true, nullable = false, length = 50)
	public String getManufactureid() {
		return this.manufactureid;
	}

	public void setManufactureid(String manufactureid) {
		this.manufactureid = manufactureid;
	}

	@Column(name = "weather", length = 50)
	public String getWeather() {
		return this.weather;
	}

	public void setWeather(String weather) {
		this.weather = weather;
	}

	@Column(name = "politicalissues", length = 50)
	public String getPoliticalissues() {
		return this.politicalissues;
	}

	public void setPoliticalissues(String politicalissues) {
		this.politicalissues = politicalissues;
	}

	@Column(name = "labourissues", length = 50)
	public String getLabourissues() {
		return this.labourissues;
	}

	public void setLabourissues(String labourissues) {
		this.labourissues = labourissues;
	}

	@Column(name = "driverissues", length = 50)
	public String getDriverissues() {
		return this.driverissues;
	}

	public void setDriverissues(String driverissues) {
		this.driverissues = driverissues;
	}

}
