package neu.edu.entity;
// Generated 15-Dec-2022, 10:11:56 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rawmaterial generated by hbm2java
 */
@Entity
@Table(name = "rawmaterial", catalog = "manufacture")
public class Rawmaterial implements java.io.Serializable {

	private String materialid;
	private Integer itemid;
	private String itemname;
	private Integer availability;
	private String manufactureid;

	public Rawmaterial() {
	}

	public Rawmaterial(String materialid) {
		this.materialid = materialid;
	}

	public Rawmaterial(String materialid, Integer itemid, String itemname, Integer availability, String manufactureid) {
		this.materialid = materialid;
		this.itemid = itemid;
		this.itemname = itemname;
		this.availability = availability;
		this.manufactureid = manufactureid;
	}

	@Id

	@Column(name = "materialid", unique = true, nullable = false, length = 50)
	public String getMaterialid() {
		return this.materialid;
	}

	public void setMaterialid(String materialid) {
		this.materialid = materialid;
	}

	@Column(name = "itemid")
	public Integer getItemid() {
		return this.itemid;
	}

	public void setItemid(Integer itemid) {
		this.itemid = itemid;
	}

	@Column(name = "itemname", length = 50)
	public String getItemname() {
		return this.itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	@Column(name = "availability")
	public Integer getAvailability() {
		return this.availability;
	}

	public void setAvailability(Integer availability) {
		this.availability = availability;
	}

	@Column(name = "manufactureid", length = 50)
	public String getManufactureid() {
		return this.manufactureid;
	}

	public void setManufactureid(String manufactureid) {
		this.manufactureid = manufactureid;
	}

}
