package neu.edu.entity;
// Generated 14-Dec-2022, 10:01:30 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Supplierorder generated by hbm2java
 */
@Entity
@Table(name = "supplierorder", catalog = "manufacture")
public class Supplierorder implements java.io.Serializable {

	private int orderid;
	private String itemname;
	private Integer itemid;
	private Integer units;
	private Integer cost;
	private String supplierid;
	private String status;
	private String manufactureid;

	public Supplierorder() {
	}

	public Supplierorder(int orderid) {
		this.orderid = orderid;
	}

	public Supplierorder(int orderid, String itemname, Integer itemid, Integer units, Integer cost, String supplierid,
			String status, String manufactureid) {
		this.orderid = orderid;
		this.itemname = itemname;
		this.itemid = itemid;
		this.units = units;
		this.cost = cost;
		this.supplierid = supplierid;
		this.status = status;
		this.manufactureid = manufactureid;
	}

	@Id

	@Column(name = "orderid", unique = true, nullable = false)
	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	@Column(name = "itemname", length = 50)
	public String getItemname() {
		return this.itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	@Column(name = "itemid")
	public Integer getItemid() {
		return this.itemid;
	}

	public void setItemid(Integer itemid) {
		this.itemid = itemid;
	}

	@Column(name = "units")
	public Integer getUnits() {
		return this.units;
	}

	public void setUnits(Integer units) {
		this.units = units;
	}

	@Column(name = "cost")
	public Integer getCost() {
		return this.cost;
	}

	public void setCost(Integer cost) {
		this.cost = cost;
	}

	@Column(name = "supplierid", length = 50)
	public String getSupplierid() {
		return this.supplierid;
	}

	public void setSupplierid(String supplierid) {
		this.supplierid = supplierid;
	}

	@Column(name = "status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "manufactureid", length = 50)
	public String getManufactureid() {
		return this.manufactureid;
	}

	public void setManufactureid(String manufactureid) {
		this.manufactureid = manufactureid;
	}

}
